name: Goshen Groundwater Research
title: Goshen Groundwater Research
description: Website for the physics groundwater research group at Goshen College

baseurl: '/~groundwater'
url: "http://people.goshen.edu"

destination: '/home/groundwater/mypages/'   
